#!/bin/bash

# Minimal debloat script for Poco M4 Pro 5G
# Removes all non-essential Xiaomi, Google, Facebook and bloat apps
# Keeps core system and Play Store functionality

packages=(
# --- MIUI & Xiaomi bloatware ---
"com.miui.msa.global"
"com.miui.analytics"
"com.miui.bugreport"
"com.miui.weather2"
"com.miui.qr"
"com.miui.yellowpage"
"com.miui.freeform"
"com.miui.systemui.carriers.overlay"
"com.miui.fm"
"com.miui.fmservice"
"com.miui.player"
"com.miui.cloudbackup"
"com.miui.cloudservice"
"com.miui.android.fashiongallery"
"com.miui.extraphoto"
#"com.miui.misound"
"com.miui.backup"
"com.miui.phrase"
"com.miui.mediaeditor"
"com.miui.gallery"
"com.miui.screenrecorder"
"com.miui.miservice"
"com.miui.micloudsync"
"com.miui.daemon"

# Xiaomi Services / Tracking
"com.xiaomi.finddevice"
"com.xiaomi.glgm"
"com.xiaomi.payment"
"com.xiaomi.simactivate.service"
"com.xiaomi.joyose"
"com.xiaomi.ugd"
"com.xiaomi.xmsf"
"com.xiaomi.xmsfkeeper"
"com.xiaomi.calendar"
"com.xiaomi.cameratools"
"com.xiaomi.barrage"
"com.xiaomi.mipicks"
"com.xiaomi.aicr"
"com.xiaomi.discover"


# --- Facebook Bloat ---
"com.facebook.katana"
"com.facebook.services"
"com.facebook.system"
"com.facebook.appmanager"

# --- Google apps that aren't essential ---
"com.google.android.apps.maps"
"com.google.android.apps.messaging"
#"com.google.android.apps.turbo"
"com.google.android.apps.subscriptions.red"
"com.google.android.apps.wellbeing"
"com.google.android.apps.safetyhub"
"com.google.android.tts"
#"com.google.android.inputmethod.latin"
"com.google.android.projection.gearhead"
"com.google.android.marvin.talkback"
#"com.google.android.ims"
"com.google.android.adservices.api"
#"com.google.android.as"
#"com.google.android.as.oss"
#"com.google.android.ondevicepersonalization.services"
#"com.google.android.modulemetadata"
"com.google.android.cellbroadcastreceiver"
"com.google.android.cellbroadcastservice"
"com.google.android.apps.nbu.paisa.user"
"com.google.android.googlequicksearchbox"
"com.google.android.apps.restore"
#"com.google.android.configupdater"
"com.google.android.feedback"
#"com.google.android.packageinstaller"
#"com.google.android.ext.services"
#"com.google.android.ext.shared"
"com.google.android.gm"
"com.google.android.youtube"
"com.google.android.contacts"
"com.google.android.apps.googleassistant"
"com.google.android.dialer"
"com.google.android.syncadapters.calendar"
"com.google.android.gms.location.history"

# --- Debug / Test / Factory ---
#"com.goodix.gftest"
#"com.debug.loggerui"
#"com.modemdebug"
#"com.mi.AutoTest"
#"com.wingtech.secretcode"
#"com.bsp.catchlog"
#"com.factory.mmigroup"
#"com.wing.wtsarcontrol"
"cn.wps.xiaomi.abroad.lite"

# --- Misc bloat & overlays ---
"com.android.egg"
"com.android.bookmarkprovider"
#"com.android.soundpicker"
#"com.android.wallpaper.livepicker"
#"com.android.wallpapercropper"
#"com.android.wallpaperpicker"
"com.android.dreams.basic"
"com.android.apps.tag"
"com.android.hotwordenrollment.okgoogle"
"com.android.hotwordenrollment.xgoogle"
"com.android.traceur"
"com.android.printspooler"
"com.android.chrome"
"com.android.providers.downloads.ui"
"com.android.providers.downloads"
"com.android.dynsystem"
"com.android.updater"
"com.mediatek.ygps"
#"com.android.stk"
"com.android.vpndialogs"
"com.mi.android.globalFileexplorer"
"com.mi.globalminusscreen"
"com.android.mms"
"com.milink.service"
#"org.ifaa.aidl.manager"
"org.mipay.android.manager"
#"com.tencent.soter.soterserver"
)

# Loop through packages and uninstall
for pkg in "${packages[@]}"
do
  echo "Uninstalling: $pkg"
  adb shell pm uninstall --user 0 "$pkg"
done

echo "Debloat complete. Reboot your phone for changes to take effect."
